/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.proje3;

import Classes.Complaints;
import Classes.Database;
import Classes.User;
import java.awt.Image;
import java.awt.event.ActionListener;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.AEADBadTagException;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author obama
 */
public class ComplaintsInfo extends javax.swing.JFrame {

    /**
     * Creates new form ComplaintsInfo
     */
    User u;
    DefaultTableModel Tmodel;
    ArrayList<Complaints> list;

    public ComplaintsInfo(User u) {
        initComponents();
        this.u = u;
    }

    public ComplaintsInfo() {

        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnl_up = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnl_down = new javax.swing.JPanel();
        spn_product = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txta_complaint = new javax.swing.JTextArea();
        btn_submit = new javax.swing.JButton();
        btn_import = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_info = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        btn_showData = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setMinimumSize(new java.awt.Dimension(400, 300));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(400, 300));

        pnl_up.setBackground(new java.awt.Color(0, 204, 204));
        pnl_up.setMinimumSize(new java.awt.Dimension(400, 40));
        pnl_up.setPreferredSize(new java.awt.Dimension(400, 40));

        jLabel1.setFont(new java.awt.Font("Verdana", 3, 13)); // NOI18N
        jLabel1.setText("Complaints Information");

        javax.swing.GroupLayout pnl_upLayout = new javax.swing.GroupLayout(pnl_up);
        pnl_up.setLayout(pnl_upLayout);
        pnl_upLayout.setHorizontalGroup(
            pnl_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_upLayout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        pnl_upLayout.setVerticalGroup(
            pnl_upLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_upLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jSplitPane1.setTopComponent(pnl_up);

        pnl_down.setBackground(new java.awt.Color(0, 204, 204));
        pnl_down.setMinimumSize(new java.awt.Dimension(398, 200));
        pnl_down.setPreferredSize(new java.awt.Dimension(398, 200));

        spn_product.setModel(new javax.swing.SpinnerListModel(new String[] {"TV", "Radio", "Labtop", "Headphones"}));

        jLabel2.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        jLabel2.setText("Product");

        jLabel3.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        jLabel3.setText("Complaint");

        txta_complaint.setColumns(20);
        txta_complaint.setRows(5);
        jScrollPane1.setViewportView(txta_complaint);

        btn_submit.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        btn_submit.setText("Submit");
        btn_submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_submitActionPerformed(evt);
            }
        });

        btn_import.setText("import photo");
        btn_import.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_importActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_downLayout = new javax.swing.GroupLayout(pnl_down);
        pnl_down.setLayout(pnl_downLayout);
        pnl_downLayout.setHorizontalGroup(
            pnl_downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_downLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnl_downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_downLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(111, 111, 111)
                        .addComponent(spn_product, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_downLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(82, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_downLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnl_downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_downLayout.createSequentialGroup()
                        .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_downLayout.createSequentialGroup()
                        .addComponent(btn_import)
                        .addGap(124, 124, 124))))
        );
        pnl_downLayout.setVerticalGroup(
            pnl_downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_downLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(spn_product, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGroup(pnl_downLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_downLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl_downLayout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jLabel3)))
                .addGap(11, 11, 11)
                .addComponent(btn_submit, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(btn_import)
                .addContainerGap())
        );

        jSplitPane1.setRightComponent(pnl_down);

        jTabbedPane1.addTab("new complaint", jSplitPane1);

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        jPanel2.setBackground(new java.awt.Color(0, 204, 204));

        tbl_info.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "product", "status", "sloution"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tbl_info);

        jLabel4.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jLabel4.setText("Information table");

        btn_showData.setFont(new java.awt.Font("Verdana", 3, 10)); // NOI18N
        btn_showData.setText("Show data");
        btn_showData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_showDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(btn_showData, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btn_showData, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        jPanel1.add(jPanel2);

        jTabbedPane1.addTab("Check status", jPanel1);

        getContentPane().add(jTabbedPane1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_showDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_showDataActionPerformed
        Tmodel = (DefaultTableModel) tbl_info.getModel();
        Tmodel.setRowCount(0);
        try {
            list = Database.addToTable(u.getId());
            for (int i = 0; i < list.size(); i++) {
                Tmodel.insertRow(Tmodel.getRowCount(), new Object[]{list.get(i).getProduct(), list.get(i).getStatus(), list.get(i).getSloution()});
            }
            tbl_info.setModel(Tmodel);

        } catch (SQLException ex) {
            Logger.getLogger(ComplaintsInfo.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_btn_showDataActionPerformed

    private void btn_submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_submitActionPerformed
        try {
            // TODO add your handling code here:
            Database.Insert("INSERT INTO complaints(id,detailsOfComplaint,product)VALUES('" + u.getId() + "','" + txta_complaint.getText() + "','" + spn_product.getValue().toString() + "')");
            txta_complaint.setText("");
            JOptionPane.showMessageDialog(jPanel1, "your complaint has been submitted", "info", JOptionPane.INFORMATION_MESSAGE);
        } catch (SQLException ex) {
            Logger.getLogger(ComplaintsInfo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btn_submitActionPerformed

    private void btn_importActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_importActionPerformed
        img f = new img();
        f.setVisible(true);
    }//GEN-LAST:event_btn_importActionPerformed

    /**
     * @param args the command line arguments
     */
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_import;
    private javax.swing.JButton btn_showData;
    private javax.swing.JButton btn_submit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel pnl_down;
    private javax.swing.JPanel pnl_up;
    private javax.swing.JSpinner spn_product;
    private javax.swing.JTable tbl_info;
    private javax.swing.JTextArea txta_complaint;
    // End of variables declaration//GEN-END:variables
}
